# Site Settings
title: My Curriculum Vitae
url: 'http://bynyden.com'
baseurl: '/online_cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Mats VdN
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Fancy a creative mind for your next project? Search no further.'

#sidebar links
dob: 15/09/1990
gender: Male
email: mats@bynyden.com
#phone: 012 345 6789
website: bynyden.com #do not add http://
#linkedin: alandoe
github: devbynyden
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-115376140-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
